
// A Iterable object:
let myObject = {
   // ......

   // A property (A method with key Symbol.iterator).
   [Symbol.iterator] :  function()  {
       // Code...
   }

}


// Your code
let myArray = [ "Tom", "Jerry", "Donald"];

// Equivalent to the code:
// (Generated by Javascript)
let myArray = {

   0 : "Tom",
   1 : "Jerry",
   2 : "Donald",

   [Symbol.iterator] : function()  {
      // Code generated by Javascript...
   }

};
